import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="h-full">
      <Head>
        <title>Hamworks</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <main className="bg-black text-white font-orbitron h-full">
        <section
          className="w-full bg-[url('/images/bg-hamworks.png')]
          bg-fixed bg-center bg-no-repeat bg-cover 
          relative shadow-hero"
        >
          <h1 className="w-full text-center text-4xl absolute top-20 left-0 ">
            Hamworks
          </h1>
          <span
            aria-hidden="true"
            className="text-decoration text-vertical font-medium absolute 
            top-10 pr-1 tracking-widest"
          >
            - 2018-2022 Projects -
          </span>
          <div
            aria-hidden="true"
            className="h-hero mb-[-2rem]"
          ></div>
          <div
            className="text-center bg-[url('/images/bg-welcome.png')] bg-center
            bg-no-repeat bg-cover pt-4"
          >
            <p className="text-2xl">Welcome!</p>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores
              iure voluptate ab quis labore, maxime optio distinctio. Nesciunt
              explicabo nulla possimus nam veniam ipsum quam repudiandae, magni
              obcaecati ipsa sapiente.
            </p>
          </div>
        </section>
      </main>

      <footer></footer>
    </div>
  );
}
