import Head from "next/head";
import Main from "../components/Home/Main";
import Footer from "../components/Home/Footer";
import Copyright from "../components/Home/Copyright";
import Intro from "../components/Home/Intro";
import Welcome from "../components/Home/Welcome";
import Projects from "../components/Home/Projects";
import About from "../components/Home/About";
import Contact from "../components/Home/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hamworks</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Main>
        <Intro />
        <Welcome />
        <Projects />
        <About />
        <Contact />
      </Main>
      <Footer />
      <Copyright />
    </>
  );
}
